name: "Compile Swift"

on:
  workflow_dispatch:
  push:
    paths:
      - "c/**"
      - ".github/**"
  pull_request:

permissions:
  contents: read

jobs:
  swiftpm:
    name: SwiftPM - Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-15', 'ubuntu-22.04', 'windows-2022']
        swift-version: ['6.0.3']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: sushichop/gha-swift-env@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Build and test a Swift package
        run: |
          swift build -v -c release