name: "Compile Swift"

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/**"
  pull_request:

permissions:
  contents: read

jobs:
  build-non-musl:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        swift: ["6.0.3"]
    steps:
      - uses: SwiftyLab/setup-swift@v1.9.1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Get swift version
        run: swift --version
      - name: Build and test a Swift package on windows/linux
        run: |
          cd swift && swift build -v -c release
      - name: Build a Swift package on Macos
        if: matrix.os == 'macos-latest'
        run: |
          cd swift 
          swift build -c release --triple x86_64-apple-macosx
          swift build -c release --triple arm64-apple-macosx
          lipo .build/arm64-apple-macosx/release/swift .build/x86_64-apple-macosx/release/swift -create -output swift.universal
  build-musl:
    name: Swift with Musl
    runs-on: macos-latest
    steps:
      - uses: SwiftyLab/setup-swift@v1.9.1
        with:
          swift-version: "6.0.3"
      - uses: actions/checkout@v4
      - name: Get swift version
        run: swift --version
      - name: Install Swift Musl SDK
        run: |
          swift sdk install https://download.swift.org/swift-6.0.3-release/static-sdk/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum 67f765e0030e661a7450f7e4877cfe008db4f57f177d5a08a6e26fd661cdd0bd
      - name: Build and test a Swift package
        run: |
          cd swift && swift build -c release  --swift-sdk x86_64-swift-linux-musl
      