name: "Compile Swift"

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/**"
  pull_request:

permissions:
  contents: read

jobs:
  swiftpm:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.0.3"]
    steps:
      - uses: SwiftyLab/setup-swift@v1.9.1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Get swift version
        run: swift --version
      - name: Build and test a Swift package
        run: |
          cd swift && swift build -v -c release